/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useEffect } from 'react';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('models/people.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {});

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Armature' rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Body.geometry}
          material={nodes.Body.material}
          skeleton={nodes.Body.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Bottoms.geometry}
          material={materials.Bottommat}
          skeleton={nodes.Bottoms.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Eyelashes.geometry}
          material={materials.Eyelashmat}
          skeleton={nodes.Eyelashes.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Eyes.geometry}
          material={nodes.Eyes.material}
          skeleton={nodes.Eyes.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Hair.geometry}
          material={materials.Hairmat}
          skeleton={nodes.Hair.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Shoes.geometry}
          material={materials.Shoesmat}
          skeleton={nodes.Shoes.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Tops.geometry}
          material={materials.Topmat}
          skeleton={nodes.Tops.skeleton}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips_1} />
      </group>
    </group>
  );
}

useGLTF.preload('/people.glb');
